# Generated by Django 4.2.4 on 2023-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('data_source', models.CharField(blank=True, max_length=10, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('food_img', models.CharField(blank=True, max_length=1000, null=True)),
                ('recipe_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('serving', models.CharField(blank=True, max_length=10, null=True)),
                ('category_high_level', models.CharField(blank=True, max_length=20, null=True)),
                ('category_mid_level', models.CharField(blank=True, max_length=20, null=True)),
                ('category_low_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('재료1', models.CharField(blank=True, max_length=50, null=True)),
                ('재료2', models.CharField(blank=True, max_length=50, null=True)),
                ('재료3', models.CharField(blank=True, max_length=50, null=True)),
                ('재료4', models.CharField(blank=True, max_length=50, null=True)),
                ('재료5', models.CharField(blank=True, max_length=50, null=True)),
                ('재료6', models.CharField(blank=True, max_length=50, null=True)),
                ('재료7', models.CharField(blank=True, max_length=50, null=True)),
                ('재료8', models.CharField(blank=True, max_length=50, null=True)),
                ('재료9', models.CharField(blank=True, max_length=50, null=True)),
                ('재료10', models.CharField(blank=True, max_length=50, null=True)),
                ('재료1_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료2_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료3_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료4_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료5_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료6_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료7_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료8_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료9_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('재료10_정량', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
    ]
